name: Check Package
on:
  push:
    branches:
      - main
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - uses: MeilCli/npm-update-check-action@v5
