name: 'Dependency review'
on:
  push:
    branches: [ "master" ]
permissions:
  contents: read
  # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Npm check updates'
        uses: Fzwael/ncu-action@v1.3.0
